# Generated by Django 6.1.1 on 2026-09-25 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Overview')),
                ('eligibility', models.TextField(verbose_name='Eligibility Criteria')),
                ('required_documents', models.TextField(verbose_name='Required Documents')),
                ('adoption_process', models.TextField(verbose_name='Step-by-Step Process')),
                ('contact_information', models.TextField(verbose_name='Official Contact Information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adoption Information',
                'verbose_name_plural': 'Adoption Information Hub',
            },
        ),
        migrations.CreateModel(
            name='CareOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Description')),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified Organization'), ('Rejected', 'Rejected')], default='Verified', max_length=20, verbose_name='Verification Status')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Care Organization',
                'verbose_name_plural': 'Care Organizations',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('Adoption', 'Adoption Process'), ('Donations', 'Donations & Gifts'), ('Child_Safety', 'Privacy & Child Safety'), ('General', 'General Questions')], default='General', max_length=30)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Child Alias / Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('description', models.TextField(verbose_name='Background / About Child')),
                ('health_status', models.CharField(default='Healthy', max_length=150, verbose_name='Health Status')),
                ('adoption_status', models.CharField(choices=[('Available', 'Available for Adoption Inquiries'), ('In_Process', 'In Process'), ('Supported', 'Supported by Donor Gifts'), ('Adopted', 'Adopted')], default='Available', max_length=20, verbose_name='Status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.careorganization', verbose_name='Care Organization')),
            ],
            options={
                'verbose_name': 'Child Profile',
                'verbose_name_plural': 'Child Profiles',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type', models.CharField(choices=[('Books_Stationery', 'Educational & Books'), ('Clothes', 'Clothing & Footwear'), ('Toys_Games', 'Toys & Recreation'), ('Health_Nutrition', 'Nutrition & Health Supplies'), ('Other', 'Other Support')], max_length=30)),
                ('description', models.TextField(verbose_name='Gift Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('Pledged', 'Pledged by Donor'), ('Dispatched', 'Dispatched / In Transit'), ('Received', 'Received by Organization'), ('Acknowledged', 'Verified & Acknowledged with Proof')], default='Pledged', max_length=20)),
                ('tracking_reference', models.CharField(blank=True, max_length=100, verbose_name='Courier / Tracking Ref')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to=settings.AUTH_USER_MODEL, verbose_name='Donor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='core.careorganization', verbose_name='Care Organization')),
            ],
            options={
                'verbose_name': 'Gift / Support',
                'verbose_name_plural': 'Gifts / Supports',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Impact Message / Proof Note')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Proof Photo')),
                ('feedback_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending Admin Verification'), ('Verified', 'Verified & Public Proof')], default='Verified', max_length=20)),
                ('gift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_feedback', to='core.gift')),
            ],
            options={
                'verbose_name': 'Transparency Feedback',
                'verbose_name_plural': 'Transparency Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='MilestoneUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Milestone Title')),
                ('description', models.TextField(verbose_name='Progress & Growth Update')),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='milestones/', verbose_name='Update Photo')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.child')),
            ],
            options={
                'verbose_name': 'Milestone & Growth Update',
                'verbose_name_plural': 'Milestone Updates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Gift_Update', 'Gift Tracking Update'), ('Milestone', 'Milestone & Growth Update'), ('Anniversary', 'Anniversary Reminder'), ('System', 'System Notification')], default='System', max_length=25)),
                ('message', models.TextField()),
                ('notification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-notification_date'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Story Title')),
                ('story_description', models.TextField(verbose_name='Success Story Details')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Story Image')),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.careorganization')),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Campaign / Wish Title')),
                ('item_name', models.CharField(max_length=150, verbose_name='Item Name')),
                ('description', models.TextField(verbose_name='Description & Purpose')),
                ('quantity_needed', models.PositiveIntegerField(default=1, verbose_name='Quantity Needed')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Quantity Received')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High Priority'), ('Urgent', 'Urgent Need')], default='Medium', max_length=15)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Partially_Fulfilled', 'Partially Fulfilled'), ('Fulfilled', 'Fully Fulfilled')], default='Open', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='core.careorganization', verbose_name='Care Organization')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='wishlist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to='core.wishlist', verbose_name='Matched Wishlist Item'),
        ),
    ]
